// <auto-generated />
using System;
using AIInterviewPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIInterviewPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519102335_Add_Feedback_Recommendation")]
    partial class Add_Feedback_Recommendation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AnswerEvaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ClarityScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("clarity_score");

                    b.Property<DateTime>("EvaluatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("evaluated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("InterviewAnswerId")
                        .HasColumnType("bigint")
                        .HasColumnName("interview_answer_id");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<decimal?>("RelevanceScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("relevance_score");

                    b.Property<decimal?>("StructureScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("structure_score");

                    b.HasKey("Id");

                    b.HasIndex("InterviewAnswerId")
                        .IsUnique();

                    b.ToTable("answer_evaluations", null, t =>
                        {
                            t.HasCheckConstraint("chk_eval_clarity_score", "[clarity_score] IS NULL OR ([clarity_score] >= 0 AND [clarity_score] <= 100)");

                            t.HasCheckConstraint("chk_eval_overall_score", "[overall_score] IS NULL OR ([overall_score] >= 0 AND [overall_score] <= 100)");

                            t.HasCheckConstraint("chk_eval_relevance_score", "[relevance_score] IS NULL OR ([relevance_score] >= 0 AND [relevance_score] <= 100)");

                            t.HasCheckConstraint("chk_eval_structure_score", "[structure_score] IS NULL OR ([structure_score] >= 0 AND [structure_score] <= 100)");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_auth_email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("authentication_accounts", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Feedback", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AnswerEvaluationId")
                        .HasColumnType("bigint")
                        .HasColumnName("answer_evaluation_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("FeedbackContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("feedback_content");

                    b.Property<string>("FeedbackType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("feedback_type");

                    b.HasKey("Id");

                    b.HasIndex("AnswerEvaluationId")
                        .HasDatabaseName("idx_feedbacks_evaluation_id");

                    b.ToTable("feedbacks", null, t =>
                        {
                            t.HasCheckConstraint("chk_feedback_type", "[feedback_type] IS NULL OR [feedback_type] IN ('CLARITY', 'STRUCTURE', 'RELEVANCE', 'COMMUNICATION', 'OVERALL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ImprovementSuggestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FeedbackId")
                        .HasColumnType("bigint")
                        .HasColumnName("feedback_id");

                    b.Property<string>("PriorityLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("priority_level");

                    b.Property<string>("SuggestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("suggestion_content");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId")
                        .HasDatabaseName("idx_suggestions_feedback_id");

                    b.ToTable("improvement_suggestions", null, t =>
                        {
                            t.HasCheckConstraint("chk_suggestion_priority", "[priority_level] IS NULL OR [priority_level] IN ('LOW', 'MEDIUM', 'HIGH')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnswerText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer_text");

                    b.Property<long>("InterviewQuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("interview_question_id");

                    b.Property<long>("InterviewSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("interview_session_id");

                    b.Property<DateTime>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("InterviewQuestionId")
                        .HasDatabaseName("idx_interview_answers_question_id");

                    b.HasIndex("InterviewSessionId")
                        .HasDatabaseName("idx_interview_answers_session_id");

                    b.ToTable("interview_answers", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("AI")
                        .HasColumnName("generated_by");

                    b.Property<long>("InterviewSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("interview_session_id");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_content");

                    b.Property<long?>("QuestionTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_template_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_interview_questions_category_id");

                    b.HasIndex("InterviewSessionId")
                        .HasDatabaseName("idx_interview_questions_session_id");

                    b.HasIndex("QuestionTemplateId");

                    b.ToTable("interview_questions", null, t =>
                        {
                            t.HasCheckConstraint("chk_question_generated_by", "[generated_by] IN ('AI', 'TEMPLATE', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<string>("SessionStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("IN_PROGRESS")
                        .HasColumnName("session_status");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("TargetJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_job_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetJobId")
                        .HasDatabaseName("idx_interview_sessions_target_job_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_interview_sessions_user_id");

                    b.ToTable("interview_sessions", null, t =>
                        {
                            t.HasCheckConstraint("chk_session_status", "[session_status] IN ('IN_PROGRESS', 'COMPLETED', 'CANCELLED')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("MANUAL")
                        .HasColumnName("source_type");

                    b.Property<long>("TargetJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_job_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetJobId")
                        .HasDatabaseName("idx_job_descriptions_target_job_id");

                    b.ToTable("job_descriptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_jd_source_type", "[source_type] IN ('MANUAL', 'UPLOAD', 'URL', 'AI_GENERATED')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.QuestionCategory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("question_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Behavioral"
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Technical"
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Communication"
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Problem Solving"
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.QuestionTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("CreatedByAdminId")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_admin_id");

                    b.Property<string>("DifficultyLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("difficulty_level");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("TemplateContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("template_content");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CreatedByAdminId");

                    b.ToTable("question_templates", null, t =>
                        {
                            t.HasCheckConstraint("chk_template_difficulty", "[difficulty_level] IS NULL OR [difficulty_level] IN ('EASY', 'MEDIUM', 'HARD')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ReadinessScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("OVERALL")
                        .HasColumnName("score_type");

                    b.Property<long?>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId");

                    b.HasIndex("UserId", "CalculatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_readiness_scores_user_time");

                    b.ToTable("readiness_scores", null, t =>
                        {
                            t.HasCheckConstraint("chk_readiness_score_range", "[score] >= 0 AND [score] <= 100");

                            t.HasCheckConstraint("chk_readiness_score_type", "[score_type] IN ('OVERALL', 'TECHNICAL', 'COMMUNICATION', 'BEHAVIORAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Recommendation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long?>("FeedbackId")
                        .HasColumnType("bigint")
                        .HasColumnName("feedback_id");

                    b.Property<string>("RecommendationContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("recommendation_content");

                    b.Property<string>("RecommendationType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recommendation_type");

                    b.Property<long?>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId");

                    b.HasIndex("SkillGapAnalysisId")
                        .HasDatabaseName("idx_recommendations_analysis_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_recommendations_user_id");

                    b.ToTable("recommendations", null, t =>
                        {
                            t.HasCheckConstraint("chk_recommendation_type", "[recommendation_type] IS NULL OR [recommendation_type] IN ('SKILL', 'INTERVIEW', 'COMMUNICATION', 'ROADMAP', 'GENERAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.RequiredSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ImportanceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("importance_level");

                    b.Property<long>("JobDescriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_description_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId")
                        .HasDatabaseName("idx_required_skills_jd_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("idx_required_skills_skill_id");

                    b.HasIndex("JobDescriptionId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("uq_required_skill");

                    b.ToTable("required_skills", null, t =>
                        {
                            t.HasCheckConstraint("chk_required_skill_importance", "[importance_level] IS NULL OR [importance_level] IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ParsedContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parsed_content");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_resumes_user_id");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill_name");

                    b.Property<string>("SkillType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_type");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Communication",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Problem Solving",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Teamwork",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "SQL",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Java",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Python",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "System Design",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Data Analysis",
                            SkillType = "Technical Skill"
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GapDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gap_description");

                    b.Property<string>("GapLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gap_level");

                    b.Property<long>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId")
                        .HasDatabaseName("idx_skill_gaps_analysis_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("idx_skill_gaps_skill_id");

                    b.HasIndex("SkillGapAnalysisId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("uq_skill_gap");

                    b.ToTable("skill_gaps", null, t =>
                        {
                            t.HasCheckConstraint("chk_skill_gap_level", "[gap_level] IS NULL OR [gap_level] IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("COMPLETED")
                        .HasColumnName("analysis_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("JobDescriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_description_id");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint")
                        .HasColumnName("resume_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId")
                        .HasDatabaseName("idx_skill_gap_analyses_jd_id");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("idx_skill_gap_analyses_resume_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_skill_gap_analyses_user_id");

                    b.ToTable("skill_gap_analyses", null, t =>
                        {
                            t.HasCheckConstraint("chk_sga_status", "[analysis_status] IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.StrengthWeaknessReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("report_type");

                    b.Property<long>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId");

                    b.ToTable("strength_weakness_reports", null, t =>
                        {
                            t.HasCheckConstraint("chk_sw_report_type", "[report_type] IN ('STRENGTH', 'WEAKNESS')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("experience_level");

                    b.Property<string>("Industry")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("industry");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_target_jobs_user_id");

                    b.ToTable("target_jobs", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("USER")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_status", "[status] IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED')");

                            t.HasCheckConstraint("chk_users_user_type", "[user_type] IN ('USER', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CareerGoal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("career_goal");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("education_level");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.WeakCommunicationPattern", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FeedbackId")
                        .HasColumnType("bigint")
                        .HasColumnName("feedback_id");

                    b.Property<string>("PatternDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pattern_description");

                    b.Property<string>("PatternName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("pattern_name");

                    b.HasKey("Id");

                    b.HasIndex("FeedbackId")
                        .HasDatabaseName("idx_patterns_feedback_id");

                    b.ToTable("weak_communication_patterns", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AnswerEvaluation", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.InterviewAnswer", "InterviewAnswer")
                        .WithOne("AnswerEvaluation")
                        .HasForeignKey("AIInterviewPlatform.Domain.Enities.AnswerEvaluation", "InterviewAnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_evaluation_answer");

                    b.Navigation("InterviewAnswer");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithOne("AuthenticationAccount")
                        .HasForeignKey("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Feedback", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.AnswerEvaluation", "AnswerEvaluation")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AnswerEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_feedback_evaluation");

                    b.Navigation("AnswerEvaluation");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ImprovementSuggestion", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.Feedback", "Feedback")
                        .WithMany("ImprovementSuggestions")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_suggestion_feedback");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewAnswer", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.InterviewQuestion", "InterviewQuestion")
                        .WithMany("InterviewAnswers")
                        .HasForeignKey("InterviewQuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_answer_question");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.InterviewSession", "InterviewSession")
                        .WithMany("InterviewAnswers")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_answer_session");

                    b.Navigation("InterviewQuestion");

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewQuestion", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.QuestionCategory", "Category")
                        .WithMany("InterviewQuestions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_question_category");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.InterviewSession", "InterviewSession")
                        .WithMany("InterviewQuestions")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_session");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.QuestionTemplate", "QuestionTemplate")
                        .WithMany("InterviewQuestions")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_question_template");

                    b.Navigation("Category");

                    b.Navigation("InterviewSession");

                    b.Navigation("QuestionTemplate");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewSession", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.TargetJob", "TargetJob")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("TargetJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_session_target_job");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_session_user");

                    b.Navigation("TargetJob");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.TargetJob", "TargetJob")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("TargetJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jd_target_job");

                    b.Navigation("TargetJob");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.QuestionTemplate", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.QuestionCategory", "Category")
                        .WithMany("QuestionTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_template_category");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "CreatedByAdmin")
                        .WithMany("CreatedQuestionTemplates")
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_template_admin");

                    b.Navigation("Category");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ReadinessScore", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("ReadinessScores")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_score_analysis");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("ReadinessScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_score_user");

                    b.Navigation("SkillGapAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Recommendation", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.Feedback", "Feedback")
                        .WithMany("Recommendations")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendation_feedback");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("Recommendations")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_recommendation_analysis");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("Recommendations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_recommendation_user");

                    b.Navigation("Feedback");

                    b.Navigation("SkillGapAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.RequiredSkill", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.JobDescription", "JobDescription")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_required_skill_jd");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Skill", "Skill")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_required_skill_skill");

                    b.Navigation("JobDescription");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGap", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("SkillGaps")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_gap_analysis");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Skill", "Skill")
                        .WithMany("SkillGaps")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_skill_gap_skill");

                    b.Navigation("Skill");

                    b.Navigation("SkillGapAnalysis");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.JobDescription", "JobDescription")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_jd");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Resume", "Resume")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_resume");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_user");

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.StrengthWeaknessReport", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("StrengthWeaknessReports")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sw_report_analysis");

                    b.Navigation("SkillGapAnalysis");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("TargetJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_job_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.UserProfile", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("AIInterviewPlatform.Domain.Enities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.WeakCommunicationPattern", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.Feedback", "Feedback")
                        .WithMany("WeakCommunicationPatterns")
                        .HasForeignKey("FeedbackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pattern_feedback");

                    b.Navigation("Feedback");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AnswerEvaluation", b =>
                {
                    b.Navigation("Feedbacks");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Feedback", b =>
                {
                    b.Navigation("ImprovementSuggestions");

                    b.Navigation("Recommendations");

                    b.Navigation("WeakCommunicationPatterns");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewAnswer", b =>
                {
                    b.Navigation("AnswerEvaluation");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewQuestion", b =>
                {
                    b.Navigation("InterviewAnswers");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewSession", b =>
                {
                    b.Navigation("InterviewAnswers");

                    b.Navigation("InterviewQuestions");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.Navigation("RequiredSkills");

                    b.Navigation("SkillGapAnalyses");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.QuestionCategory", b =>
                {
                    b.Navigation("InterviewQuestions");

                    b.Navigation("QuestionTemplates");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.QuestionTemplate", b =>
                {
                    b.Navigation("InterviewQuestions");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.Navigation("SkillGapAnalyses");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Skill", b =>
                {
                    b.Navigation("RequiredSkills");

                    b.Navigation("SkillGaps");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.Navigation("ReadinessScores");

                    b.Navigation("Recommendations");

                    b.Navigation("SkillGaps");

                    b.Navigation("StrengthWeaknessReports");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.Navigation("InterviewSessions");

                    b.Navigation("JobDescriptions");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.User", b =>
                {
                    b.Navigation("AuthenticationAccount");

                    b.Navigation("CreatedQuestionTemplates");

                    b.Navigation("InterviewSessions");

                    b.Navigation("ReadinessScores");

                    b.Navigation("Recommendations");

                    b.Navigation("Resumes");

                    b.Navigation("SkillGapAnalyses");

                    b.Navigation("TargetJobs");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
