// <auto-generated />
using System;
using AIInterviewPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace AIInterviewPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601020000_AddSkillFocusToInterviewQuestion")]
    partial class AddSkillFocusToInterviewQuestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.InterviewQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("AI")
                        .HasColumnName("generated_by");

                    b.Property<long>("InterviewSessionId")
                        .HasColumnType("bigint")
                        .HasColumnName("interview_session_id");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question_content");

                    b.Property<long?>("QuestionTemplateId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_template_id");

                    b.Property<string>("SkillFocus")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill_focus")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("idx_interview_questions_category_id");

                    b.HasIndex("InterviewSessionId")
                        .HasDatabaseName("idx_interview_questions_session_id");

                    b.HasIndex("QuestionTemplateId");

                    b.ToTable("interview_questions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
