// <auto-generated />
using System;
using AIInterviewPlatform.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIInterviewPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519101115_Add_SkillGapAnalysis")]
    partial class Add_SkillGapAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_auth_email");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("authentication_accounts", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("MANUAL")
                        .HasColumnName("source_type");

                    b.Property<long>("TargetJobId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_job_id");

                    b.HasKey("Id");

                    b.HasIndex("TargetJobId")
                        .HasDatabaseName("idx_job_descriptions_target_job_id");

                    b.ToTable("job_descriptions", null, t =>
                        {
                            t.HasCheckConstraint("chk_jd_source_type", "[source_type] IN ('MANUAL', 'UPLOAD', 'URL', 'AI_GENERATED')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ReadinessScore", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("ScoreType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("OVERALL")
                        .HasColumnName("score_type");

                    b.Property<long?>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId");

                    b.HasIndex("UserId", "CalculatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("idx_readiness_scores_user_time");

                    b.ToTable("readiness_scores", null, t =>
                        {
                            t.HasCheckConstraint("chk_readiness_score_range", "[score] >= 0 AND [score] <= 100");

                            t.HasCheckConstraint("chk_readiness_score_type", "[score_type] IN ('OVERALL', 'TECHNICAL', 'COMMUNICATION', 'BEHAVIORAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.RequiredSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ImportanceLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("importance_level");

                    b.Property<long>("JobDescriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_description_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId")
                        .HasDatabaseName("idx_required_skills_jd_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("idx_required_skills_skill_id");

                    b.HasIndex("JobDescriptionId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("uq_required_skill");

                    b.ToTable("required_skills", null, t =>
                        {
                            t.HasCheckConstraint("chk_required_skill_importance", "[importance_level] IS NULL OR [importance_level] IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ParsedContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("parsed_content");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_resumes_user_id");

                    b.ToTable("resumes", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Skill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("skill_name");

                    b.Property<string>("SkillType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("skill_type");

                    b.HasKey("Id");

                    b.HasIndex("SkillName")
                        .IsUnique();

                    b.ToTable("skills", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Communication",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Problem Solving",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Teamwork",
                            SkillType = "Soft Skill"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "SQL",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Java",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Python",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "System Design",
                            SkillType = "Technical Skill"
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SkillName = "Data Analysis",
                            SkillType = "Technical Skill"
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGap", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GapDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gap_description");

                    b.Property<string>("GapLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("gap_level");

                    b.Property<long>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.Property<long>("SkillId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId")
                        .HasDatabaseName("idx_skill_gaps_analysis_id");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("idx_skill_gaps_skill_id");

                    b.HasIndex("SkillGapAnalysisId", "SkillId")
                        .IsUnique()
                        .HasDatabaseName("uq_skill_gap");

                    b.ToTable("skill_gaps", null, t =>
                        {
                            t.HasCheckConstraint("chk_skill_gap_level", "[gap_level] IS NULL OR [gap_level] IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("COMPLETED")
                        .HasColumnName("analysis_status");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("JobDescriptionId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_description_id");

                    b.Property<long>("ResumeId")
                        .HasColumnType("bigint")
                        .HasColumnName("resume_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId")
                        .HasDatabaseName("idx_skill_gap_analyses_jd_id");

                    b.HasIndex("ResumeId")
                        .HasDatabaseName("idx_skill_gap_analyses_resume_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_skill_gap_analyses_user_id");

                    b.ToTable("skill_gap_analyses", null, t =>
                        {
                            t.HasCheckConstraint("chk_sga_status", "[analysis_status] IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.StrengthWeaknessReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("report_type");

                    b.Property<long>("SkillGapAnalysisId")
                        .HasColumnType("bigint")
                        .HasColumnName("skill_gap_analysis_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillGapAnalysisId");

                    b.ToTable("strength_weakness_reports", null, t =>
                        {
                            t.HasCheckConstraint("chk_sw_report_type", "[report_type] IN ('STRENGTH', 'WEAKNESS')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("experience_level");

                    b.Property<string>("Industry")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("industry");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("idx_target_jobs_user_id");

                    b.ToTable("target_jobs", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("ACTIVE")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("USER")
                        .HasColumnName("user_type");

                    b.HasKey("Id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("chk_users_status", "[status] IN ('ACTIVE', 'INACTIVE', 'LOCKED', 'DELETED')");

                            t.HasCheckConstraint("chk_users_user_type", "[user_type] IN ('USER', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.UserProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CareerGoal")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("career_goal");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EducationLevel")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("education_level");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("full_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithOne("AuthenticationAccount")
                        .HasForeignKey("AIInterviewPlatform.Domain.Enities.AuthenticationAccount", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.TargetJob", "TargetJob")
                        .WithMany("JobDescriptions")
                        .HasForeignKey("TargetJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_jd_target_job");

                    b.Navigation("TargetJob");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.ReadinessScore", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("ReadinessScores")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_score_analysis");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("ReadinessScores")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_score_user");

                    b.Navigation("SkillGapAnalysis");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.RequiredSkill", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.JobDescription", "JobDescription")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_required_skill_jd");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Skill", "Skill")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_required_skill_skill");

                    b.Navigation("JobDescription");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resume_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGap", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("SkillGaps")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_gap_analysis");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Skill", "Skill")
                        .WithMany("SkillGaps")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_skill_gap_skill");

                    b.Navigation("Skill");

                    b.Navigation("SkillGapAnalysis");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.JobDescription", "JobDescription")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("JobDescriptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_jd");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.Resume", "Resume")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_resume");

                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("SkillGapAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sga_user");

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.StrengthWeaknessReport", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", "SkillGapAnalysis")
                        .WithMany("StrengthWeaknessReports")
                        .HasForeignKey("SkillGapAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sw_report_analysis");

                    b.Navigation("SkillGapAnalysis");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithMany("TargetJobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_target_job_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.UserProfile", b =>
                {
                    b.HasOne("AIInterviewPlatform.Domain.Enities.User", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("AIInterviewPlatform.Domain.Enities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profile_user");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.JobDescription", b =>
                {
                    b.Navigation("RequiredSkills");

                    b.Navigation("SkillGapAnalyses");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Resume", b =>
                {
                    b.Navigation("SkillGapAnalyses");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.Skill", b =>
                {
                    b.Navigation("RequiredSkills");

                    b.Navigation("SkillGaps");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.SkillGapAnalysis", b =>
                {
                    b.Navigation("ReadinessScores");

                    b.Navigation("SkillGaps");

                    b.Navigation("StrengthWeaknessReports");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.TargetJob", b =>
                {
                    b.Navigation("JobDescriptions");
                });

            modelBuilder.Entity("AIInterviewPlatform.Domain.Enities.User", b =>
                {
                    b.Navigation("AuthenticationAccount");

                    b.Navigation("ReadinessScores");

                    b.Navigation("Resumes");

                    b.Navigation("SkillGapAnalyses");

                    b.Navigation("TargetJobs");

                    b.Navigation("UserProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
